version: '3.8'

services:
  localstack:
    image: localstack/localstack:2.3
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services
    environment:
      - DEBUG=1
      - SERVICES=sqs,lambda,iam,eventbridge,s3
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
